[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags =
    -save-temps=obj
    -fverbose-asm
; 시리얼 모니터 속도 설정 (필요시 추가)
monitor_port = COM3 
monitor_speed = 9600  ; -> Atmel AVR

;upload_port = COM3/
# upload_speed = 115200 ; -> Atmel AVR