[env:uno]
platform = atmelavr
board = uno
framework = arduino


build_flags = 
    -Wno-incompatible-pointer-types




; build_flags =  // 어셈블리 파일 새성 
    ; -save-temps=obj  // 빌드 디렉토리에 중간 산출물 파일(.s, .i, .ii 등)을 생성합니다
    ; -fverbose-asm   // 어셈블리 파일 내에 추가 정보를 포함하도록 합니다
# 컴파일 후 .pio/build/[환경명]/ 폴더로 이동하면, .s 파일이 생성
# 예시 경로: .pio/build/uno/src/main.cpp.s

# 컴파일이 끝난 후, .elf 파일을 objdump로 디스어셈블 하면 전체 어셈블리 코드를 한 파일로 정리
# C:\Users\{USERNAME}\.platformio\packages\toolchain-atmelavr\bin\avr-objdump.exe  
#
# cd .pio/build/uno
# avr-objdump -S -d firmware.elf > firmware.s
# C:\Users\{USERNAME}\.platformio\packages\toolchain-atmelavr\bin\avr-objdump  -S -d firmware.elf > firmware.s
# firmware.s에 어셈블리 코드와 C 소스가 병기되어 저장



; extra_scripts = post_build.py



; 시리얼 모니터 속도 설정 (필요시 추가)
; monitor_port = COM3 
; monitor_speed = 9600  ; -> Atmel AVR

; ;upload_port = COM3/
; # upload_speed = 115200 ; -> Atmel AVR


;; task libs
; lib_deps =
;     arkhipenko/TaskScheduler @ ^3.7.0